# Generated by Django 5.0.6 on 2026-02-25 08:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vertical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=200)),
                ("color_hex", models.CharField(default="#3B82F6", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "base_pay",
                    models.PositiveIntegerField(
                        default=250000, help_text="Monthly base ₦"
                    ),
                ),
                (
                    "transport_pay",
                    models.PositiveIntegerField(
                        default=80000, help_text="Monthly transport ₦"
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=4, default="0.0110", max_digits=5
                    ),
                ),
            ],
            options={
                "db_table": "core_verticals",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("base_pay", models.PositiveIntegerField(default=50000)),
                ("transport_pay", models.PositiveIntegerField(default=40000)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=4, default="0.0400", max_digits=5
                    ),
                ),
                ("order_target", models.PositiveIntegerField(default=2000)),
                ("revenue_target", models.PositiveBigIntegerField(default=3000000)),
                (
                    "vertical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zones",
                        to="core.vertical",
                    ),
                ),
            ],
            options={
                "db_table": "core_zones",
                "ordering": ["vertical", "name"],
            },
        ),
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateField()),
                ("bike_plate", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="riders",
                        to="core.zone",
                    ),
                ),
            ],
            options={
                "db_table": "core_riders",
                "ordering": ["zone", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                ("business_type", models.CharField(max_length=100)),
                ("owner_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("watch", "Watch"),
                            ("inactive", "Inactive"),
                            ("churned", "Churned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("onboarded_at", models.DateField()),
                ("last_order_at", models.DateTimeField(blank=True, null=True)),
                ("cac_number", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merchants",
                        to="core.zone",
                    ),
                ),
            ],
            options={
                "db_table": "core_merchants",
                "ordering": ["zone", "business_name"],
            },
        ),
        migrations.CreateModel(
            name="MerchantSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("orders_placed", models.PositiveIntegerField(default=0)),
                ("orders_fulfilled", models.PositiveIntegerField(default=0)),
                ("orders_returned", models.PositiveIntegerField(default=0)),
                ("gross_revenue", models.PositiveBigIntegerField(default=0)),
                ("avg_order_value", models.PositiveBigIntegerField(default=0)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="core.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "core_merchant_snapshots",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["merchant", "date"],
                        name="core_mercha_merchan_379484_idx",
                    ),
                    models.Index(fields=["date"], name="core_mercha_date_950efc_idx"),
                ],
                "unique_together": {("merchant", "date")},
            },
        ),
        migrations.CreateModel(
            name="RiderSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("orders_completed", models.PositiveIntegerField(default=0)),
                ("orders_rejected", models.PositiveIntegerField(default=0)),
                ("orders_failed", models.PositiveIntegerField(default=0)),
                (
                    "km_covered",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("revenue_generated", models.PositiveBigIntegerField(default=0)),
                ("online_minutes", models.PositiveIntegerField(default=0)),
                (
                    "peak_orders",
                    models.PositiveIntegerField(
                        default=0, help_text="Orders during peak hours"
                    ),
                ),
                (
                    "avg_delivery_mins",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "csat_sum",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("csat_count", models.PositiveIntegerField(default=0)),
                (
                    "ghost_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minutes GPS active while rider status is offline",
                    ),
                ),
                ("has_ghost_flag", models.BooleanField(default=False)),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="core.rider",
                    ),
                ),
            ],
            options={
                "db_table": "core_rider_snapshots",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["rider", "date"], name="core_rider__rider_i_be6b66_idx"
                    ),
                    models.Index(fields=["date"], name="core_rider__date_0f7e48_idx"),
                ],
                "unique_together": {("rider", "date")},
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned to Rider"),
                            ("picked_up", "Picked Up"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("pickup_address", models.TextField()),
                ("delivery_address", models.TextField()),
                ("delivery_fee", models.PositiveIntegerField(default=0)),
                (
                    "order_value",
                    models.PositiveIntegerField(default=0, help_text="Value of goods"),
                ),
                (
                    "km_distance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "csat_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=200)),
                ("failure_reason", models.CharField(blank=True, max_length=200)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="core.merchant",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="core.rider",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="core.zone",
                    ),
                ),
            ],
            options={
                "db_table": "core_orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["rider", "status"],
                        name="core_orders_rider_i_a420f3_idx",
                    ),
                    models.Index(
                        fields=["merchant", "status"],
                        name="core_orders_merchan_2a2de6_idx",
                    ),
                    models.Index(
                        fields=["zone", "created_at"],
                        name="core_orders_zone_id_6fba9d_idx",
                    ),
                ],
            },
        ),
    ]
