# Generated by Django 5.0.6 on 2026-03-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_hierarchy"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="core_orders_zone_id_6fba9d_idx",
        ),
        migrations.AlterField(
            model_name="hub",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hubs",
                to="core.zone",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["hub", "created_at"], name="core_orders_hub_id_d6d871_idx"
            ),
        ),
    ]
