# Generated by Django 5.0.6 on 2026-02-25 08:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("merchant", "Merchant"), ("rider", "Rider")],
                        max_length=20,
                    ),
                ),
                (
                    "msg_type",
                    models.CharField(
                        choices=[
                            ("promotion", "Promotion"),
                            ("reminder", "Reminder"),
                            ("drip", "Drip"),
                            ("seasonal", "Seasonal"),
                            ("performance", "Performance"),
                            ("incentive", "Incentive"),
                            ("operational", "Operational"),
                            ("general", "General"),
                        ],
                        max_length=30,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "subject",
                    models.CharField(
                        blank=True, help_text="Email subject only", max_length=200
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Supports {name}, {orders}, {zone}, {captain} tokens"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comms_templates",
                "ordering": ["audience", "msg_type", "label"],
            },
        ),
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("merchant", "Merchant"), ("rider", "Rider")],
                        max_length=20,
                    ),
                ),
                (
                    "recipient_filter",
                    models.CharField(
                        default="all",
                        help_text="all | active | watch | inactive | critical | atrisk | flagged",
                        max_length=30,
                    ),
                ),
                (
                    "channels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("sms", "SMS"),
                                ("whatsapp", "WhatsApp"),
                                ("email", "Email"),
                                ("inapp", "In-App (Rider)"),
                            ],
                            max_length=20,
                        ),
                        default=list,
                        help_text="Merchant: sms/whatsapp/email. Rider: inapp",
                        size=None,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vertical",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scope to entire vertical",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcasts",
                        to="core.vertical",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scope to single zone",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcasts",
                        to="core.zone",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comms.messagetemplate",
                    ),
                ),
            ],
            options={
                "db_table": "comms_broadcasts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BroadcastDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("inapp", "In-App (Rider)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_msg", models.TextField(blank=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="comms.broadcast",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="core.merchant",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="core.rider",
                    ),
                ),
            ],
            options={
                "db_table": "comms_deliveries",
                "indexes": [
                    models.Index(
                        fields=["broadcast", "status"],
                        name="comms_deliv_broadca_aaa47e_idx",
                    ),
                    models.Index(
                        fields=["rider", "is_read"],
                        name="comms_deliv_rider_i_3fa0c5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RiderInAppNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("body", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="comms.broadcast",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.rider",
                    ),
                ),
            ],
            options={
                "db_table": "comms_rider_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["rider", "is_read"],
                        name="comms_rider_rider_i_ab4e88_idx",
                    )
                ],
            },
        ),
    ]
